### ISSUE TITLE
Add runtime styling examples

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#367]
_This ticket was originally an issue in the (now deprecated) Android SDK repo and has been moved to this repo. Originally created by_ @tobrun 

Our current SDK example page needs more runtime style examples. An idea I have been having is porting the GL-JS examples on this topic to Android. This should help our users to navigate and learn code differences more easily but on the other hand this a great benchmark to test the implementations on gl-native vs gl-js.

Most of these examples have already been created by @cammace in [mapbox-demo](https://github.com/mapbox/mapbox-android-demo/) or have been implemented in the [testapp]( https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp). We just need to get them on the website. 

Below is a list of the examples shown in gl-js examples page:

## Layers
 - [x] Show and hide layers -> https://github.com/mapbox/android-sdk/issues/205
 - [x] Create and style clusters -> https://github.com/mapbox/android-sdk/issues/205
 - [x] Create a heatmap from points -> https://github.com/mapbox/android-sdk/issues/205
 - [x] Change a layer's color with buttons -> https://github.com/mapbox/android-sdk/issues/205
 - [x] Add a new layer below labels -> https://github.com/mapbox/android-sdk/issues/205
 - [x] Add a GeoJSON line (Replace older example?) -> https://github.com/mapbox/android-sdk/issues/205
 - [x] Add a GeoJSON polygon
 - [ ] Add multiple geometries from one GeoJSON source
 - [ ] Draw GeoJSON points
 - [ ] Add an image
 - [ ] Add a video
 - [x] ~~Style circles using data-driven styling~~
 - [x] Animate a point?
 - [ ] Animate a series of images?
 - [x] Update a choropleth layer by zoom level?
 - [x] Adjust a layer's opacity -> https://github.com/mapbox/android-sdk/issues/205
 - [x] ~~Extrude polygons for 3D indoor mapping.~~
 - [x] ~~Display buildings in 3D~~

## Sources
 - [x] Add a vector tile source -> https://github.com/mapbox/android-sdk/pull/189
 - [x] Add a raster tile source
 - [x] Add a WMS source -> https://github.com/mapbox/android-sdk/issues/205
 - [x] Add a third party vector tile source (part of [this example/pr](https://github.com/mapbox/mapbox-android-demo/pull/386))
 - [x] Add live realtime data -> https://github.com/mapbox/android-sdk/issues/205
 - [ ] Create a time slider?

**Comment by cammace** [comment]
@langsmith @tobrun what is left here to tackle? This ticket is becoming pretty stale.

**Comment by tobrun** [comment]
We are getting imagesource in 5.2.0, which allows to add 'animated image'  from OP. 

The following are possible now:
Draw GeoJSON points
Add multiple geometries from one GeoJSON source

**Comment by cammace** [comment]
> Draw GeoJSON points

This is shown in the [Symbol layer](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java) example.

I've opened an individual ticket for the multiple geometries example https://github.com/mapbox/mapbox-android-demo/issues/417

Let's keep eyes on the 5.2 new features and create examples for it when the first beta becomes available. Going ahead and closing this ticket in favor of individual ones that are more trackable.
